[build]
target = "x86_64-pc-windows-msvc"

# [target.x86_64-pc-windows-msvc]
# rustflags = ["-Ctarget-feature=+crt-static"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
